name: Terraform Drift Detection

on:
 # schedule:
 #   - cron: '0 3 * * *'  # Runs daily at 3 AM UTC

 # push:
 #   branches:
 #     - main
  workflow_dispatch:
jobs:
  drift-check:
    runs-on: ubuntu-latest
    env:
      #OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Refresh
      run: terraform refresh

    - name: Terraform Plan
      run: terraform plan -detailed-exitcode

    - name: Check for Drift
      run: |
        if [ $? -eq 2 ]; then
          echo "⚠️ Drift detected! Manual changes may have occurred."
          # Optionally send alert or create GitHub issue
        else
          echo "✅ No drift detected."
        fi
