name: Terraform Drift Detection

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC

jobs:
  drift-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Refresh
      run: terraform refresh

    - name: Terraform Plan
      run: terraform plan -detailed-exitcode

    - name: Check for Drift
      run: |
        if [ $? -eq 2 ]; then
          echo "⚠️ Drift detected! Manual changes may have occurred."
          # Optionally send alert or create GitHub issue
        else
          echo "✅ No drift detected."
        fi
